from typing import Callable

def generator_numbers(text: str): # Generator function to yield numbers from text
    words = text.split()
    for word in words:
        try:
            yield float(word) # Convert word to float
        except ValueError:
            continue

def sum_profit(text: str, func: Callable): # Function to sum numbers generated by the provided function
    total = 0.0
    for number in func(text):
        total += number
    return total

text = """Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід,
         доповнений додатковими надходженнями 27.45 і 324 доларів."""
total_income = sum_profit(text, generator_numbers)
print(f"Total income: {total_income}")